apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: nginx-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
