apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: nginx-service
  port:
    targetPort: {{ .Values.service.port }}
